/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'accessible-text-blue-1': '(--accessible-text-blue-1)',
                'accessible-text-blue-2': '(--accessible-text-blue-2)',
                'solid-blue-1': '(--solid-blue-1)',
                'solid-blue-2': '(--solid-blue-2)',
                'border-blue-1': '(--border-blue-1)',
                'border-blue-2': '(--border-blue-2)',
                'border-blue-3': '(--border-blue-3)',
                'interactive-blue-1': '(--interactive-blue-1)',
                'interactive-blue-2': '(--interactive-blue-2)',
                'interactive-blue-3': '(--interactive-blue-3)',
                'background-blue-1': '(--background-blue-1)',
                'background-blue-2': '(--background-blue-2)',
                'accessible-text-gray-1': '(--accessible-text-gray-1)',
                'accessible-text-gray-2': '(--accessible-text-gray-2)',
                'solid-gray-1': '(--solid-gray-1)',
                'solid-gray-2': '(--solid-gray-2)',
                'border-gray-1': '(--border-color-gray-1)',
                'border-gray-2': '(--border-color-gray-2)',
                'border-gray-3': '(--border-color-gray-3)',
                'interactive-gray-1': '(---interactive-gray-1)',
                'interactive-gray-2': '(---interactive-gray-2)',
                'interactive-gray-3': '(---interactive-gray-3)',
                'background-gray-1': '(--background-gray-1)',
                'background-gray-2': '(--background-gray-2)',
            },
            fontFamily: {
                poppinsBold: ['PoppinsBold', 'sans-serif'],
                poppinsItalic: ['PoppinsBoldItalic', 'sans-serif'],
                poppinsLight: ['PoppinsBoldLight', 'sans-serif'],
                poppinsMedium: ['PoppinsBoldMedium', 'sans-serif'],
                poppinsRegular: ['PoppinsBoldRegular', 'sans-serif'],
            },
            spacing: {
                180: '32rem',
            },
        },
    },
    plugins: [],
};
