/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'accessible-text-blue-1': 'var(--accessible-text-blue-1)',
                'accessible-text-blue-2': 'var(--accessible-text-blue-2)',
                'solid-blue-1': 'var(--solid-blue-1)',
                'solid-blue-2': 'var(--solid-blue-2)',
                'border-blue-1': 'var(--border-blue-1)',
                'border-blue-2': 'var(--border-blue-2)',
                'border-blue-3': 'var(--border-blue-3)',
                'interactive-blue-1': 'var(--interactive-blue-1)',
                'interactive-blue-2': 'var(--interactive-blue-2)',
                'interactive-blue-3': 'var(--interactive-blue-3)',
                'background-blue-1': 'var(--background-blue-1)',
                'background-blue-2': 'var(--background-blue-2)',

                'accessible-text-gray-1': 'var(--accessible-text-gray-1)',
                'accessible-text-gray-2': 'var(--accessible-text-gray-2)',
                'solid-gray-1': 'var(--solid-gray-1)',
                'solid-gray-2': 'var(--solid-gray-2)',
                'border-gray-1': 'var(--border-color-gray-1)',
                'border-gray-2': 'var(--border-color-gray-2)',
                'border-gray-3': 'var(--border-color-gray-3)',
                'interactive-gray-1': 'var(---interactive-gray-1)',
                'interactive-gray-2': 'var(---interactive-gray-2)',
                'interactive-gray-3': 'var(---interactive-gray-3)',
                'background-gray-1': 'var(--background-gray-1)',
                'background-gray-2': 'var(--background-gray-2)',

                'dark-accessible-text-blue-1': 'var(--dark-accessible-text-blue-1)',
                'dark-accessible-text-blue-2': 'var(--dark-accessible-text-blue-2)',
                'dark-solid-blue-1': 'var(--dark-solid-blue-1)',
                'dark-solid-blue-2': 'var(--dark-solid-blue-2)',
                'dark-border-blue-1': 'var(--dark-border-blue-1)',
                'dark-border-blue-2': 'var(--dark-border-blue-2)',
                'dark-border-blue-3': 'var(--dark-border-blue-3)',
                'dark-interactive-blue-1': 'var(--dark-interactive-blue-1)',
                'dark-interactive-blue-2': 'var(--dark-interactive-blue-2)',
                'dark-interactive-blue-3': 'var(--dark-interactive-blue-3)',
                'dark-background-blue-1': 'var(--dark-background-blue-1)',
                'dark-background-blue-2': 'var(--dark-background-blue-2)',

                'dark-accessible-text-gray-1': 'var(--dark-accessible-text-gray-1)',
                'dark-accessible-text-gray-2': 'var(--dark-accessible-text-gray-2)',
                'dark-solid-gray-1': 'var(--dark-solid-gray-1)',
                'dark-solid-gray-2': 'var(--dark-solid-gray-2)',
                'dark-border-gray-1': 'var(--dark-border-color-gray-1)',
                'dark-border-gray-2': 'var(--dark-border-color-gray-2)',
                'dark-border-gray-3': 'var(--dark-border-color-gray-3)',
                'dark-interactive-gray-1': 'var(--dark--interactive-gray-1)',
                'dark-interactive-gray-2': 'var(--dark--interactive-gray-2)',
                'dark-interactive-gray-3': 'var(--dark--interactive-gray-3)',
                'dark-background-gray-1': 'var(--dark-background-gray-1)',
                'dark-background-gray-2': 'var(--dark-background-gray-2)',
            },
            fontFamily: {
                poppinsBold: ['PoppinsBold', 'sans-serif'],
                poppinsItalic: ['PoppinsBoldItalic', 'sans-serif'],
                poppinsLight: ['PoppinsBoldLight', 'sans-serif'],
                poppinsMedium: ['PoppinsBoldMedium', 'sans-serif'],
                poppinsRegular: ['PoppinsBoldRegular', 'sans-serif'],
            },
            spacing: {
                180: '32rem',
            },
        },
    },
    plugins: [],
};
